-- Migration 029: Public audit request capture
-- Allows anonymous landing-page visitors to submit a website for follow-up.

CREATE TABLE IF NOT EXISTS public.audit_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_url TEXT NOT NULL,
    domain_url TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'landing_page',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processed', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_requests_created_at
    ON public.audit_requests(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_requests_domain_url
    ON public.audit_requests(domain_url);

ALTER TABLE public.audit_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can create audit requests" ON public.audit_requests;
CREATE POLICY "Public can create audit requests"
    ON public.audit_requests
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can read audit requests" ON public.audit_requests;
CREATE POLICY "Authenticated users can read audit requests"
    ON public.audit_requests
    FOR SELECT
    TO authenticated
    USING (true);

